import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

import { FileUpload } from 'primereact/fileupload';

import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";



export default function Contact() {

  const [file, setFile] = useState(null);


  const onFileChange = event => {

    setFile(event.target.files[0]);
    console.log(file)

  };

  const test = () => {
    console.log(file.size)
  }

  async function handleOnSubmit(e) {
    e.preventDefault();
    const formData = {};
    Array.from(e.currentTarget.elements).forEach(field => {
      if (!field.name) return;
      formData[field.name] = field.value;
    })
    fetch('/api/mail', {
      method: 'post',
      body: JSON.stringify(formData),
    })
  }

  return (
    <div>
      <Head>
        <title>Pole Printing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{}}>
        <style jsx>
          {`
            label {
              display: block;
              margin-bottom: 0.2em;
            }
            
            button {
              color: white;
              background-color: blueviolet;
              padding: 0.4em 1em;
              border: none;
              border-radius: 0.2em;
            }
          `}
        </style>
        <form method='post' onSubmit={handleOnSubmit}>
          <p>
            <label htmlFor='name'>Name</label>
            <input type='text' name='name' />
          </p>
          <p>
            <label htmlFor='email'>Email</label>
            <input type='text' name='email' />
          </p>
          <p>
            <label htmlFor='message'>Message</label>
            <input type='text' name='message' />
          </p>
          <p>
            <label htmlFor='attachment'>Message</label>
            <input type='file' name='attachment' />
          </p>
          <FileUpload name='uploaderThing' url='/api/fileupload'></FileUpload>
          <p>
            <button>Submit</button>
          </p>
        </form>
      </div>
          
      <div>
        <p>Next Images with Cloudinary Dynamic URLs: https://www.youtube.com/watch?v=n7VeENVQntY</p>
      </div>

    </div>
  )
}
