export const productList = [

    {
        id: 'business-cards',
        title: 'Business Cards',
        description: `These Business Cards are really sharp! Die Cut available at extra cost.`,
        minimumOrderQuantity: '100 Cards',
        quantities: [],
        quantitiesLabel: 'Packs of',
        sizes: ['3.5" x 2"'],
        images: null, // []
        materials: ['12 Point', '14 Point', '16 Point', 'Other Stocks Available'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Card Numbers', 'Full Bleed'],
        tags: ['Cards'],
    },
    {
        id: 'brochures',
        title: 'Brochures',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '100 Copies',
        quantities: ['Coated', 'Uncoated'],
        quantitiesLabel: 'Coating',
        sizes: ['5.5" x 8.5"', 'up to', '11" x 17"'],
        images: null, // []
        materials: ['60lbs', '70lbs', '80lbs', '100lbs'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Coated', 'Two-Sided Printing', 'Perferation', 'Copy/Issue Numbers', 'Full Bleed'],
        tags: ['trucking'],
    },
    {
        id: 'carbonless-forms',
        title: 'Carbonless Forms',
        description: 'Carbonless Forms can be used to instanatly create multiple copies of a single hand-written form to be shared with clients or staff.',
        minimumOrderQuantity: '250 Forms',
        quantities: ['250 Sets', 'Books Also Available'],
        quantitiesLabel: 'Single Sets of',
        sizes: ['4.25" x 5.5"', 'up to', '11" x 17"'],
        images: null, // []
        materials: ['One Copy plus Original (Two Part: White and Canary)', 'Two Copies plus Original (Three Part: White, Canary and Pink)', 'Three Copies plus Original (Four Part: White, Canary, Pink and Goldenrod)'],
        materialLabel: 'Copies per Form',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        printLabel: 'Crease Option',
        optionalFeatures: ['Perferation', 'Page/Invoice Numbers', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['Carbonless', 'Forms', 'Invoices', 'Daily Log Sheets', 'Weigh Tickets', 'Daily Inspection Sheets', 'Receiving Slips', 'Packing Slips', 'Three Part Form', 'Multi-Part Form', 'Multi-Page Form'],
    },
    {
        id: 'door-hangers',
        title: 'Door Hangers',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '100 Hangers',
        quantities: [],
        sizes: ['3.5" x 8.5"', 'Custom Sizes Available'],
        images: null, // []
        materials: ['80lbs Uncoated Card Stock'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Page/Invoice Numbers', 'Full Bleed'],
        tags: ['trucking'],
    },
    {
        id: 'envelopes',
        title: 'Envelopes',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '500 Envelopes',
        quantities: ['Regular', 'Window', 'Window Outline'],
        quantitiesLabel: 'Style',
        sizes: [
            'No. 9 (3 7/8" x 8 7/8")', 'No. 10 (4 1/8" x 9 1/2")'
        ],
        images: null, // []
        materials: [],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Window', 'Security', 'Full Bleed'],
        tags: ['Security Envelopes', 'Windowed Envelopes', 'Two-Sided Printing'],
    },
    {
        id: 'labels-stickers',
        title: 'Labels & Stickers',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Labels',
        quantities: [],
        quantitiesLabel: 'Packs of',
        sizes: ['Any Size'],
        images: null, // []
        materials: ['60lbs Matte Litho, Freezer Stock (Can be laminated)'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Perferation', 'Full Bleed'],
        tags: ['trucking'],
    },
    {
        id: 'letterheads',
        title: 'Letterheads',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Sheets',
        quantities: [],
        quantitiesLabel: 'Packs of',
        sizes: ['8.5" x 11"'],
        images: null, // []
        materials: ['20lbs White Bond'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Copy Numbers', 'Full Bleed'],
        tags: ['trucking'],
    },
    {
        id: 'note-sheets',
        title: 'Note Sheets / Graph Paper',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '10 Pads',
        quantities: ['25', '50', '100'],
        quantitiesLabel: 'Pads of',
        sizes: ['4.25" x 5.5"', '5.5" x 8.5"', '8.5" x 11"'],
        images: null, // []
        materials: ['20lbs Bond'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Page/Invoice Numbers', 'Full Bleed'],
        tags: ['Scratch Sheets', 'Notepad'],
    },
    {
        id: 'postcards',
        title: 'Postcards',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Prints',
        quantities: [],
        quantitiesLabel: 'Sets of',
        sizes: ['4" x 6" (Standard)', 'Other Sizes Available'],
        images: null, // []
        materials: ['12 Point', '14 Point', '16 Point'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Laminated', 'Card Slits', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['Pocket Folders'],
    },
    {
        id: 'personalized-cheques',
        title: 'Personalized Cheques',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Folders',
        quantities: [],
        quantitiesLabel: 'Packs of',
        sizes: ['9" x 12"', '9" x 14.5"'],
        images: null, // []
        materials: ['12 Point', '14 Point'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Perferation', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['trucking'],
    },
    {
        id: 'presentation-folders',
        title: 'Presentation Folders',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Folders',
        quantities: ['One Side', 'Both Sides'],
        quantitiesLabel: 'Business Card Slits on Inside Pockets',
        sizes: ['9" x 12"', '9" x 14.5"'],
        images: null, // []
        materials: ['14 Point (Coated Covered)'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Perferation', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['trucking'],
    },
    {
        id: 'tickets',
        title: 'Tickets',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '10 Tickets',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Books of',
        sizes: ['Any Size'],
        images: null, // []
        materials: ['Any Stock'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Stapled Books', 'Two-Sided Printing', 'Perferation', 'Ticket Numbers', 'Full Bleed'],
        tags: ['Stag & Doe', 'Raffle', 'Dance Tickets', 'Fundraising'],
    },
]
