export const productList = [
    {
        id: 'carbonless-forms',
        title: 'Carbonless Forms',
        description: 'Carbonless Forms can be used to instanatly create multiple copies of a single hand-written form to be shared with clients or staff.',
        minimumOrderQuantity: '250 Forms',
        quantities: ['25', '50'],
        quantitiesLabel: 'Books of',
        sizes: ['original', 'special'],
        images: null, // []
        materials: ['One Copy plus Original (Two Part)', 'Two Copies plus Original (Three Part)', 'Three Copies plus Original (Four Part)'],
        materialLabel: 'Copies per Form',
        materialColors: ['White Original, Red/Yellow/Green Parts'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Perferation', 'Page/Invoice Numbers', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['Carbonless', 'Forms', 'Invoices', 'Daily Log Sheets', 'Weigh Tickets', 'Daily Inspection Sheets', 'Receiving Slips', 'Packing Slips', 'Three Part Form', 'Multi-Part Form', 'Multi-Page Form'],
    },
    {
        id: 'envelopes',
        title: 'Envelopes',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Envelopes',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Packs of',
        sizes: [
            '**Envelope Size**',
        ],
        images: null, // []
        materials: ['No. 9 Paper', 'No. 10 Paper'],
        materialLabel: 'Material',
        materialColors: ['White', 'Brown', 'Other???'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Window', 'Security', 'Full Bleed'],
        tags: ['Security Envelopes', 'Windowed Envelopes', 'Two-Sided Printing'],
    },
    {
        id: 'labels-stickers',
        title: 'Labels & Stickers',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Sheets',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Packs of',
        sizes: ['Any Size'],
        images: null, // []
        materials: ['Paper', 'Synthetic'],
        materialLabel: 'Material',
        materialColors: ['Any Colour'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Perferation', 'Full Bleed'],
        tags: ['trucking'],
    },
    {
        id: 'letterheads',
        title: 'Letterheads',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Sheets',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Packs of',
        sizes: ['4.25" x 5.5"', '5.5" x 8.5"', '8.5" x 11"', '12" x 18"'],
        images: null, // []
        materials: ['Paper **should list thicknesses here**'],
        materialLabel: 'Material',
        materialColors: ['Any Colour'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Copy Numbers', 'Full Bleed'],
        tags: ['trucking'],
    },
    {
        id: 'brochures',
        title: 'brochures',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '100 Copies',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Packs of',
        sizes: ['Any Size'],
        images: null, // []
        materials: ['60lbs', '70lbs', '80lbs', '100lbs'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Coated', 'Two-Sided Printing', 'Perferation', 'Copy/Issue Numbers', 'Full Bleed'],
        tags: ['trucking'],
    },
    {
        id: 'note-sheets',
        title: 'Note Sheets / Graph Paper',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: 'None',
        quantities: ['25', '50', '100'],
        quantitiesLabel: 'Pads of',
        sizes: ['4.25" x 5.5"', '5.5" x 8.5"', '8.5" x 11"', '12" x 18"'],
        images: null, // []
        materials: ['20lbs Bond'],
        materialLabel: 'Material',
        materialColors: ['Any Colour'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Page/Invoice Numbers', 'Full Bleed'],
        tags: ['Scratch Sheets', 'Notepad'],
    },
    {
        id: 'postcards',
        title: 'Postcards',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '250 Prints',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Packs of',
        sizes: ['4" x 6" Standard', 'Any Other Size'],
        images: null, // []
        materials: ['12 Point', '14 Point', '16 Point'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Page/Invoice Numbers', 'Full Bleed'],
        tags: ['trucking'],
    },
    {
        id: 'posters',
        title: 'Posters',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '5 Prints',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Packs of',
        sizes: ['8.5" x 11"', '12" x 18"', 'Anything in between'],
        images: null, // []
        materials: ['20lbs Bond', '12 Point Coated', '**Others should go here**'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Perferation', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['trucking'],
    },
    {
        id: 'presentation-folders',
        title: 'Presentation Folders',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '100 Folders',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Packs of',
        sizes: ['9" x 12"'],
        images: null, // []
        materials: ['14 Point', '16 Point'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Laminated', 'Card Slits', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['Pocket Folders'],
    },
    {
        id: 'business-cards',
        title: 'Business Cards',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '100 Cards',
        quantities: ['100 or more'],
        quantitiesLabel: 'Packs of',
        sizes: ['3.5" x 2"'],
        images: null, // []
        materials: ['Any Stock'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Card Numbers', 'Full Bleed'],
        tags: ['Cards'],
    },
    {
        id: 'tickets',
        title: 'Tickets',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '10 Tickets',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Books of',
        sizes: ['Any Size'],
        images: null, // []
        materials: ['Any Stock'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Stapled Books', 'Two-Sided Printing', 'Perferation', 'Ticket Numbers', 'Full Bleed'],
        tags: ['Stag & Doe', 'Raffle', 'Dance Tickets', 'Fundraising'],
    },
    {
        id: 'door-hangers',
        title: 'Door Hangers',
        description: 'These Business Cards are really sharp!',
        minimumOrderQuantity: '100 Prints',
        quantities: ['Anything over the minimum'],
        sizes: ['3.5" x 8.5"', 'Custom Sizes Available'],
        images: null, // []
        materials: ['80lbs Cover Stock'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['Full Colour'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Page/Invoice Numbers', 'Full Bleed'],
        tags: ['trucking'],
    },
]
