export const productList = [

    {
        id: 'business-cards',
        title: 'Business Cards',
        description: `These Business Cards are really sharp! Die Cut available at extra cost.`,
        minimumOrderQuantity: '100 Cards',
        quantities: [],
        quantitiesLabel: 'Packs of',
        sizes: ['3.5" x 2"'],
        images: [
            '/img/products/businesscards2.jpg',
            '/img/products/businesscards4.jpg',
            '/img/products/businesscards5.jpg',
            '/img/products/businesscards6.jpg',
        ],
        materials: ['12 Point', '14 Point', '16 Point', 'Other Stocks Available'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Card Numbers', 'Full Bleed'],
        tags: ['Cards'],
        primaryProduct: true,
    },
    {
        id: 'brochures',
        title: 'Brochures',
        description: 'Brochures offer a detailed reference of your products and services to prospective and current clients. Direct mail campaign are a great way to increase leads, as are handouts at an event or tradeshow.',
        minimumOrderQuantity: '100 Copies',
        quantities: ['Coated', 'Uncoated'],
        quantitiesLabel: 'Coating',
        sizes: ['5.5" x 8.5"', 'up to', '11" x 17"'],
        images: [
            '/img/products/cards1.jpg', 
            '/img/products/flyer1.jpg',
        ],
        materials: ['60lbs', '70lbs', '80lbs', '100lbs'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Coated', 'Two-Sided Printing', 'Perferation', 'Copy/Issue Numbers', 'Full Bleed'],
        tags: ['trucking'],
        primaryProduct: true,
    },
    {
        id: 'carbonless-forms',
        title: 'Carbonless Forms',
        description: 'Carbonless Forms can be used to instanatly create multiple copies of a single hand-written form to be shared with clients or staff.',
        minimumOrderQuantity: '250 Forms',
        quantities: ['250 Sets', 'Books Also Available'],
        quantitiesLabel: 'Single Sets of',
        sizes: ['4.25" x 5.5"', 'up to', '11" x 17"'],
        images: [
            '/img/products/carbonlessform6.jpg',
            '/img/products/carbonlessform3.jpg',
            '/img/products/carbonlessform2.jpg',
            '/img/products/carbonlessform5.jpg',
        ],
        materials: ['One Copy plus Original (Two Part: White and Canary)', 'Two Copies plus Original (Three Part: White, Canary and Pink)', 'Three Copies plus Original (Four Part: White, Canary, Pink and Goldenrod)'],
        materialLabel: 'Copies per Form',
        materialColors: [],
        printColors: ['**What are the crease options?'],
        printLabel: 'Crease Option',
        optionalFeatures: ['Perferation', 'Page/Invoice Numbers', 'Full Bleed', 'Two-Sided Printing', 'Full Color'],
        tags: ['Carbonless', 'Forms', 'Invoices', 'Daily Log Sheets', 'Weigh Tickets', 'Daily Inspection Sheets', 'Receiving Slips', 'Packing Slips', 'Three Part Form', 'Multi-Part Form', 'Multi-Page Form'],
        primaryProduct: true,
    },
    {
        id: 'door-hangers',
        title: 'Door Hangers',
        description: 'Door Hangers offer a quick reference of your products or services to prospective clients or customers who may not always been home during your cold calling hours.',
        minimumOrderQuantity: '100 Hangers',
        quantities: [],
        sizes: ['3.5" x 8.5"', 'Custom Sizes Available'],
        images: [],
        materials: ['80lbs Uncoated Card Stock'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Page/Invoice Numbers', 'Full Bleed'],
        tags: ['trucking'],
        primaryProduct: true,
    },
    {
        id: 'envelopes',
        title: 'Envelopes',
        description: 'Custom envelopes are great for any business looking for that extra-professional touch to their correspondence. Likewise, personalized envelopes can be a fun way to celebrate mail-outs for holidays, weddings, or other special events.',
        minimumOrderQuantity: '500 Envelopes',
        quantities: ['Regular', 'Window', 'Window Outline'],
        quantitiesLabel: 'Style',
        sizes: [
            'No. 9 (3 7/8" x 8 7/8")', 'No. 10 (4 1/8" x 9 1/2")'
        ],
        images: [
            '/img/products/envelopes1.jpg',
            '/img/products/envelopes2.jpg',
        ],
        materials: [],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Window', 'Security', 'Full Bleed'],
        tags: ['Security Envelopes', 'Windowed Envelopes', 'Two-Sided Printing'],
        primaryProduct: true,
    },
    {
        id: 'labels-stickers',
        title: 'Labels & Stickers',
        description: 'Custom labels or stickers can be used in any number of situations, and offer a quick and easy solution to correct or update another document or provide further information.',
        minimumOrderQuantity: '250 Labels',
        quantities: [],
        quantitiesLabel: 'Packs of',
        sizes: ['Any Size'],
        images: null, // []
        materials: ['60lbs Matte Litho, Freezer Stock (Can be laminated)'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Perferation', 'Full Bleed'],
        tags: ['trucking'],
        primaryProduct: true,
    },
    {
        id: 'letterheads',
        title: 'Letterheads',
        description: 'A custom letterhead is essential for any business with regular printing requirements.',
        minimumOrderQuantity: '250 Sheets',
        quantities: [],
        quantitiesLabel: 'Packs of',
        sizes: ['8.5" x 11"'],
        images: null, // []
        materials: ['20lbs White Bond'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Copy Numbers', 'Full Bleed'],
        tags: ['trucking'],
        primaryProduct: true,
    },
    {
        id: 'note-sheets',
        title: 'Note Sheets / Graph Paper',
        description: 'Professional and attractive Note Sheets/Graph Paper pads are a great addition to any office. Never miss another meeting or let an idea slip your mind again!',
        minimumOrderQuantity: '10 Pads',
        quantities: ['25', '50', '100'],
        quantitiesLabel: 'Pads of',
        sizes: ['4.25" x 5.5"', '5.5" x 8.5"', '8.5" x 11"'],
        images: null, // []
        materials: ['20lbs Bond'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color'],
        optionalFeatures: ['Two-Sided Printing', 'Perferation', 'Page/Invoice Numbers', 'Full Bleed'],
        tags: ['Scratch Sheets', 'Notepad'],
        primaryProduct: true,
    },
    {
        id: 'postcards',
        title: 'Postcards',
        description: 'A postcard is a fun, professional means of letting clients know about your services or products via mail. Likewise, why not send your extended family a Christmas Card on a profesionally printed, full-color postcard?',
        minimumOrderQuantity: '250 Prints',
        quantities: [],
        quantitiesLabel: 'Sets of',
        sizes: ['4" x 6" (Standard)', 'Other Sizes Available'],
        images: null, // []
        materials: ['12 Point', '14 Point', '16 Point'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Laminated', 'Card Slits', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['Pocket Folders'],
        primaryProduct: true,
    },
    {
        id: 'personalized-cheques',
        title: 'Personalized Cheques',
        description: 'Save time, money and confusion with our fully personalized cheques. We can use a standard template if you wish as well.',
        minimumOrderQuantity: '250 Folders',
        quantities: [],
        quantitiesLabel: 'Packs of',
        sizes: ['9" x 12"', '9" x 14.5"'],
        images: null, // []
        materials: ['12 Point', '14 Point'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Perferation', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['trucking'],
        primaryProduct: true,
    },
    {
        id: 'presentation-folders',
        title: 'Presentation Folders',
        description: 'Our Presentation Folders can be printed with a variety of formats and styles, tailored to your exact needs. Your clients or co-workers will recognize your professional approach.',
        minimumOrderQuantity: '250 Folders',
        quantities: ['One Side', 'Both Sides'],
        quantitiesLabel: 'Business Card Slits on Inside Pockets',
        sizes: ['9" x 12"', '9" x 14.5"'],
        images: [
            '/img/products/presentationfolder2.jpg',
            '/img/products/presentationfolder1.jpg',
        ], 
        materials: ['14 Point (Coated Covered)'],
        materialLabel: 'Material',
        materialColors: [],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Perferation', 'Full Bleed', 'Two-Sided Printing'],
        tags: ['trucking'],
        primaryProduct: true,
    },
    {
        id: 'tickets',
        title: 'Tickets',
        description: 'Whether for a Stag and Doe, a community raffle, or an upcoming sports event, fully-customized tickets are an absolute must.',
        minimumOrderQuantity: '10 Tickets',
        quantities: ['Anything over the minimum'],
        quantitiesLabel: 'Books of',
        sizes: ['Any Size'],
        images: null, // []
        materials: ['Any Stock'],
        materialLabel: 'Material',
        materialColors: ['White'],
        printColors: ['1 Color to Full Color (One or Two Sides)'],
        optionalFeatures: ['Stapled Books', 'Two-Sided Printing', 'Perferation', 'Ticket Numbers', 'Full Bleed'],
        tags: ['Stag & Doe', 'Raffle', 'Dance Tickets', 'Fundraising'],
        primaryProduct: false,
    },
]
